!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : load_ai_train
! Description   : Variable AI Training Load
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE load_ai_trainDyn(Vnom, Pnom, f_crest, f_cblock,        &
     &   P_comp, P_rest, Tload, Tstart)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
      REAL    REALPOLE      ! Real Pole

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vnom, Pnom, f_crest
      REAL,    INTENT(IN)  :: f_cblock, P_comp
      REAL,    INTENT(IN)  :: P_rest, Tload
      REAL,    INTENT(IN)  :: Tstart

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2
      REAL     RT_1, RT_2, STOP_LD, RT_3, RT_4
      REAL     RT_5, R_LD, RT_6, RT_7, RT_8, RT_9
      REAL     RT_10, RT_11, EN_LD, RT_12, RT_13
      REAL     RT_14, RT_15, RT_16, RT_17, RT_18
      REAL     RT_19, RT_20, Rnom

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 2
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 32
      IPGB      = NPGB
      NPGB      = NPGB + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 3

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 9)
      RT_2     = STOF(ISTOF + 10)
      STOP_LD  = STOF(ISTOF + 11)
      RT_3     = STOF(ISTOF + 12)
      RT_4     = STOF(ISTOF + 13)
      RT_5     = STOF(ISTOF + 14)
      R_LD     = STOF(ISTOF + 15)
      RT_6     = STOF(ISTOF + 16)
      RT_7     = STOF(ISTOF + 17)
      IT_1     = STOI(ISTOI + 1)
      RT_8     = STOF(ISTOF + 18)
      IT_2     = STOI(ISTOI + 2)
      RT_9     = STOF(ISTOF + 19)
      RT_10    = STOF(ISTOF + 20)
      RT_11    = STOF(ISTOF + 21)
      EN_LD    = STOF(ISTOF + 22)
      RT_12    = STOF(ISTOF + 23)
      RT_13    = STOF(ISTOF + 24)
      RT_14    = STOF(ISTOF + 25)
      RT_15    = STOF(ISTOF + 26)
      RT_16    = STOF(ISTOF + 27)
      RT_17    = STOF(ISTOF + 28)
      RT_18    = STOF(ISTOF + 29)
      RT_19    = STOF(ISTOF + 30)
      RT_20    = STOF(ISTOF + 31)
      Rnom     = STOF(ISTOF + 32)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'load_ai_train.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 
      RT_17 = 1.0

! 70:[time-sig] Output of Simulation Time 
      RT_15 = TIME

! 100:[const] Real Constant 
      RT_19 = 1000000.0

! 120:[square] Square 
      RT_20 = Vnom * Vnom

! 130:[div] Divider 
      IF (ABS(Pnom) .LT. 1.0E-100) THEN
         IF (Pnom .LT. 0.0)  THEN
            Rnom = -1.0E100 * RT_20
         ELSE
            Rnom =  1.0E100 * RT_20
         ENDIF
      ELSE
         Rnom = RT_20 / Pnom
      ENDIF

! 140:[div] Divider 
      IF (ABS(P_comp) .LT. 1.0E-100) THEN
         IF (P_comp .LT. 0.0)  THEN
            RT_12 = -1.0E100 * Rnom
         ELSE
            RT_12 =  1.0E100 * Rnom
         ENDIF
      ELSE
         RT_12 = Rnom / P_comp
      ENDIF

! 150:[div] Divider 
      IF (ABS(P_rest) .LT. 1.0E-100) THEN
         IF (P_rest .LT. 0.0)  THEN
            RT_13 = -1.0E100 * Rnom
         ELSE
            RT_13 =  1.0E100 * Rnom
         ENDIF
      ELSE
         RT_13 = Rnom / P_rest
      ENDIF

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

! 170:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_15,Tstart,1.0,0.0,0.0,RVD2_1)
      RT_16 = RVD2_1(1)

! 180:[sumjct] Summing/Differencing Junctions 
      STOP_LD = + RT_17 - RT_16

! 190:[mult] Multiplier 
      RT_18 = RT_19 * STOP_LD

! 200:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_1
      RVD2_1(2) = 0.0
      RVD2_2(1) = FLOAT(NINT(STOP_LD))
      RVD2_2(2) = 0.0
      RT_2 = EMTDC_XINT(0, 0, 1, RVD1_1, 1.0, 0.0, -100.0, 1.0e+308, RVD&
     &2_2, RVD2_1)

! 210:[gain] Gain Block 
!  Gain
      RT_9 = f_cblock * RT_2

! 220:[angle_resolver] Angle Resolver 
      RT_4 = ATAN2(SIN(RT_9),COS(RT_9))

! 230:[trig] Trigonometric Functions 
!  Trig-Func
      RT_3 = SIN(RT_4)
!

! 240:[sign] Sign Function 
!  Sign Function
      IF (RT_3 .GT. 0.0) THEN
        IT_2 = 1
      ELSEIF (RT_3 .LT. 0.0) THEN
        IT_2 = -1
      ELSE
        IT_2 = 0
      ENDIF

! 250:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,0.0,REAL(IT_2),0.0,0.0,1.0,RVD2_1)
      RT_10 = RVD2_1(1)

! 260:[gain] Gain Block 
!  Gain
      RT_8 = f_crest * RT_2

! 270:[angle_resolver] Angle Resolver 
      RT_7 = ATAN2(SIN(RT_8),COS(RT_8))

! 280:[trig] Trigonometric Functions 
!  Trig-Func
      RT_6 = SIN(RT_7)
!

! 290:[sign] Sign Function 
!  Sign Function
      IF (RT_6 .GT. 0.0) THEN
        IT_1 = 1
      ELSEIF (RT_6 .LT. 0.0) THEN
        IT_1 = -1
      ELSE
        IT_1 = 0
      ENDIF

! 300:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,0.0,REAL(IT_1),0.0,0.0,1.0,RVD2_1)
      RT_11 = RVD2_1(1)

! 310:[mult] Multiplier 
      EN_LD = RT_10 * RT_11

! 320:[select] Two Input Selector 
      IF (NINT(EN_LD) .EQ. RTCI(NRTCI)) THEN
         RT_14 = RT_12
      ELSE
         RT_14 = RT_13
      ENDIF
      NRTCI = NRTCI + 1
!

! 330:[sumjct] Summing/Differencing Junctions 
      RT_5 = + RT_18 + RT_14

! 340:[realpole] Real Pole 
!  Real_Pole
      R_LD = REALPOLE(0,1,0,1.0,Tload,RT_5,0.0,-1.0E20,1.0E20)

! 350:[pgb] Output Channel 'EN_LD'

      PGB(IPGB+1) = EN_LD

! 360:[pgb] Output Channel 'R_LD'

      PGB(IPGB+2) = R_LD

! 370:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,113455360)
      CALL E_VARRLC1_EXE(0 ,SS(1) ,  (IBRCH(1)+1), 0, R_LD, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS(1) ,  (IBRCH(1)+2), 0, R_LD, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS(1) ,  (IBRCH(1)+3), 0, R_LD, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Vnom
      STOF(ISTOF + 2) = Pnom
      STOF(ISTOF + 3) = f_crest
      STOF(ISTOF + 4) = f_cblock
      STOF(ISTOF + 5) = P_comp
      STOF(ISTOF + 6) = P_rest
      STOF(ISTOF + 7) = Tload
      STOF(ISTOF + 8) = Tstart
      STOF(ISTOF + 9) = RT_1
      STOF(ISTOF + 10) = RT_2
      STOF(ISTOF + 11) = STOP_LD
      STOF(ISTOF + 12) = RT_3
      STOF(ISTOF + 13) = RT_4
      STOF(ISTOF + 14) = RT_5
      STOF(ISTOF + 15) = R_LD
      STOF(ISTOF + 16) = RT_6
      STOF(ISTOF + 17) = RT_7
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 18) = RT_8
      STOI(ISTOI + 2) = IT_2
      STOF(ISTOF + 19) = RT_9
      STOF(ISTOF + 20) = RT_10
      STOF(ISTOF + 21) = RT_11
      STOF(ISTOF + 22) = EN_LD
      STOF(ISTOF + 23) = RT_12
      STOF(ISTOF + 24) = RT_13
      STOF(ISTOF + 25) = RT_14
      STOF(ISTOF + 26) = RT_15
      STOF(ISTOF + 27) = RT_16
      STOF(ISTOF + 28) = RT_17
      STOF(ISTOF + 29) = RT_18
      STOF(ISTOF + 30) = RT_19
      STOF(ISTOF + 31) = RT_20
      STOF(ISTOF + 32) = Rnom


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE load_ai_trainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_17, RT_19

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 3

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 9)
      RT_17    = STOF(ISTOF + 28)
      RT_19    = STOF(ISTOF + 30)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'load_ai_train.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 

      RT_17 = 1.0

! 100:[const] Real Constant 

      RT_19 = 1000000.0

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 9) = RT_1
      STOF(ISTOF + 28) = RT_17
      STOF(ISTOF + 30) = RT_19


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE load_ai_trainDyn_Begin(Tload, Tstart)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Tload, Tstart

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_17, RT_19

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 3

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 
      RT_17 = 1.0

! 70:[time-sig] Output of Simulation Time 

! 100:[const] Real Constant 
      RT_19 = 1000000.0

! 120:[square] Square 

! 130:[div] Divider 

! 140:[div] Divider 

! 150:[div] Divider 

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

! 170:[compar] Two Input Comparator 

! 180:[sumjct] Summing/Differencing Junctions 

! 190:[mult] Multiplier 

! 200:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 210:[gain] Gain Block 

! 220:[angle_resolver] Angle Resolver 

! 230:[trig] Trigonometric Functions 

! 240:[sign] Sign Function 

! 250:[compare] Single Input Level Comparator 

! 260:[gain] Gain Block 

! 270:[angle_resolver] Angle Resolver 

! 280:[trig] Trigonometric Functions 

! 290:[sign] Sign Function 

! 300:[compare] Single Input Level Comparator 

! 310:[mult] Multiplier 

! 320:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 330:[sumjct] Summing/Differencing Junctions 

! 340:[realpole] Real Pole 

! 350:[pgb] Output Channel 'EN_LD'

! 360:[pgb] Output Channel 'R_LD'

! 370:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(0 ,SS(1) ,  (IBRCH(1)+1), 0)
      CALL E_VARRLC1_CFG(0 ,SS(1) ,  (IBRCH(1)+2), 0)
      CALL E_VARRLC1_CFG(0 ,SS(1) ,  (IBRCH(1)+3), 0)

      RETURN
      END

!=======================================================================

      SUBROUTINE load_ai_trainOut_Begin(Tload, Tstart)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Tload, Tstart

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_17, RT_19

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 3

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 
      RT_17 = 1.0

! 100:[const] Real Constant 
      RT_19 = 1000000.0

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

      RETURN
      END

