!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   :  Machine-Load
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn(f)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    VM3PH2        ! '3 Phase RMS Voltage Measurement'
!     SUBR    load_ai_trainDyn  ! Variable AI Training Load
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
!     SUBR    pu_basesDyn   ! Per-unit base calculator
!     SUBR    SANDH2        ! Sample and Hold

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: f

! Electrical Node Indices
      INTEGER  NT_4(3), NT_10(3)

! Control Signals
      INTEGER  mcsw, tbgo, Mactiv, BINJ, NBINJ
      INTEGER  InitGv
      REAL     VLL_TX, RT_1, RT_2, RT_3, RT_4
      REAL     RT_5, RT_6, RT_7, RT_8, RT_9
      REAL     gxtorq, abtorq, IMACA, IMACB
      REAL     IMACC, linev, VMAC(3), torq12
      REAL     telec, RT_10, Tmstdy, Ef0
      REAL     RT_11(3), If, Ef, aplt, w, RT_12
      REAL     Testdy, MVA_GEN_TX, MVA_LD
      REAL     MVA_LD_TX, RT_13, ZG_pu, LG, LGa
      REAL     LHa, LLa, RT_14, ZH_pu, LH, RT_15
      REAL     ZL_pu, Znom, LL, X1p, RT_16, RT_17
      REAL     R1p, VH(3), IH(3), PH, QH, QG
      REAL     VG(3), IG(3), PG, VL(3), IL(3), PL
      REAL     QL, blade_pos, RT_18, RT_19, RT_20
      REAL     RT_21, fnom, RT_22, RT_23, RT_24
      REAL     RT_25, ang_osc, RT_26, RT_27
      REAL     RT_28, RT_29, RT_30, RT_31, RT_32
      REAL     ang_sys, RT_33, injA, injB, injC
      REAL     inj_mag, inj(3), RT_34, PH_low
      REAL     MVA_GEN, Iinst(3), Irms, VMH, VML
      REAL     Pout, Qout, torq23, torq45, VMG

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)
      REAL     RVD1_2, RVD1_3, RVD1_4, RVD1_5
      REAL     RVD1_6, RVD1_7, RVD1_8, RVD1_9
      REAL     RVD1_10, RVD1_11, RVD1_12, RVD1_13
      REAL     RVD1_14, RVD1_15, RVD1_16, RVD1_17
      REAL     RVD1_18

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 6
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 119
      IPGB      = NPGB
      NPGB      = NPGB + 45
      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 87

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      VLL_TX   = STOF(ISTOF + 2)
      RT_1     = STOF(ISTOF + 3)
      RT_2     = STOF(ISTOF + 4)
      RT_3     = STOF(ISTOF + 5)
      RT_4     = STOF(ISTOF + 6)
      RT_5     = STOF(ISTOF + 7)
      RT_6     = STOF(ISTOF + 8)
      RT_7     = STOF(ISTOF + 9)
      RT_8     = STOF(ISTOF + 10)
      RT_9     = STOF(ISTOF + 11)
      gxtorq   = STOF(ISTOF + 12)
      abtorq   = STOF(ISTOF + 13)
      IMACA    = STOF(ISTOF + 14)
      IMACB    = STOF(ISTOF + 15)
      IMACC    = STOF(ISTOF + 16)
      linev    = STOF(ISTOF + 17)
      mcsw     = STOI(ISTOI + 1)
      torq12   = STOF(ISTOF + 21)
      telec    = STOF(ISTOF + 22)
      RT_10    = STOF(ISTOF + 23)
      Tmstdy   = STOF(ISTOF + 24)
      Ef0      = STOF(ISTOF + 25)
      If       = STOF(ISTOF + 29)
      Ef       = STOF(ISTOF + 30)
      aplt     = STOF(ISTOF + 31)
      w        = STOF(ISTOF + 32)
      RT_12    = STOF(ISTOF + 33)
      tbgo     = STOI(ISTOI + 2)
      Testdy   = STOF(ISTOF + 34)
      MVA_GEN_TX = STOF(ISTOF + 35)
      MVA_LD   = STOF(ISTOF + 36)
      MVA_LD_TX = STOF(ISTOF + 37)
      RT_13    = STOF(ISTOF + 38)
      ZG_pu    = STOF(ISTOF + 39)
      LG       = STOF(ISTOF + 40)
      LGa      = STOF(ISTOF + 41)
      LHa      = STOF(ISTOF + 42)
      LLa      = STOF(ISTOF + 43)
      RT_14    = STOF(ISTOF + 44)
      ZH_pu    = STOF(ISTOF + 45)
      LH       = STOF(ISTOF + 46)
      RT_15    = STOF(ISTOF + 47)
      ZL_pu    = STOF(ISTOF + 48)
      Znom     = STOF(ISTOF + 49)
      LL       = STOF(ISTOF + 50)
      X1p      = STOF(ISTOF + 51)
      RT_16    = STOF(ISTOF + 52)
      RT_17    = STOF(ISTOF + 53)
      Mactiv   = STOI(ISTOI + 3)
      R1p      = STOF(ISTOF + 54)
      PH       = STOF(ISTOF + 61)
      QH       = STOF(ISTOF + 62)
      QG       = STOF(ISTOF + 63)
      PG       = STOF(ISTOF + 70)
      PL       = STOF(ISTOF + 77)
      QL       = STOF(ISTOF + 78)
      blade_pos = STOF(ISTOF + 79)
      BINJ     = STOI(ISTOI + 4)
      NBINJ    = STOI(ISTOI + 5)
      RT_18    = STOF(ISTOF + 80)
      RT_19    = STOF(ISTOF + 81)
      RT_20    = STOF(ISTOF + 82)
      RT_21    = STOF(ISTOF + 83)
      fnom     = STOF(ISTOF + 84)
      RT_22    = STOF(ISTOF + 85)
      RT_23    = STOF(ISTOF + 86)
      RT_24    = STOF(ISTOF + 87)
      RT_25    = STOF(ISTOF + 88)
      ang_osc  = STOF(ISTOF + 89)
      RT_26    = STOF(ISTOF + 90)
      RT_27    = STOF(ISTOF + 91)
      RT_28    = STOF(ISTOF + 92)
      RT_29    = STOF(ISTOF + 93)
      RT_30    = STOF(ISTOF + 94)
      RT_31    = STOF(ISTOF + 95)
      RT_32    = STOF(ISTOF + 96)
      ang_sys  = STOF(ISTOF + 97)
      RT_33    = STOF(ISTOF + 98)
      injA     = STOF(ISTOF + 99)
      injB     = STOF(ISTOF + 100)
      injC     = STOF(ISTOF + 101)
      inj_mag  = STOF(ISTOF + 102)
      RT_34    = STOF(ISTOF + 106)
      PH_low   = STOF(ISTOF + 107)
      MVA_GEN  = STOF(ISTOF + 108)
      Irms     = STOF(ISTOF + 112)
      VMH      = STOF(ISTOF + 113)
      VML      = STOF(ISTOF + 114)
      Pout     = STOF(ISTOF + 115)
      Qout     = STOF(ISTOF + 116)
      InitGv   = STOI(ISTOI + 6)
      torq23   = STOF(ISTOF + 117)
      torq45   = STOF(ISTOF + 118)
      VMG      = STOF(ISTOF + 119)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         VMAC(IT_0) = STOF(ISTOF + 17 + IT_0)
         RT_11(IT_0) = STOF(ISTOF + 25 + IT_0)
         VH(IT_0) = STOF(ISTOF + 54 + IT_0)
         IH(IT_0) = STOF(ISTOF + 57 + IT_0)
         VG(IT_0) = STOF(ISTOF + 63 + IT_0)
         IG(IT_0) = STOF(ISTOF + 66 + IT_0)
         VL(IT_0) = STOF(ISTOF + 70 + IT_0)
         IL(IT_0) = STOF(ISTOF + 73 + IT_0)
         inj(IT_0) = STOF(ISTOF + 102 + IT_0)
         Iinst(IT_0) = STOF(ISTOF + 108 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_4(IT_0) = NODE(INODE + 9 + IT_0)
         NT_10(IT_0) = NODE(INODE + 27 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[load_ai_train] Variable AI Training Load 
      CALL load_ai_trainDyn(0.48, 80.0, 0.001, 0.001, 1.0, 0.5, 0.001, 2&
     &.0)


! 30:[const] Real Constant 'VLL_TX'
      VLL_TX = 345.0

! 40:[const] Real Constant 'fnom'
      fnom = 60.0

! 50:[const] Real Constant 'ZG_pu'
      ZG_pu = 0.075

! 60:[const] Real Constant 'MVA_GEN'
      MVA_GEN = 60.0

! 70:[const] Real Constant 'ZH_pu'
      ZH_pu = 0.025

! 80:[const] Real Constant 'LGa'
      LGa = 94800.0

! 90:[const] Real Constant 'ZL_pu'
      ZL_pu = 0.025

! 100:[const] Real Constant 'MVA_GEN_TX'
      MVA_GEN_TX = 450.0

! 110:[const] Real Constant 'LHa'
      LHa = 31600.0

! 120:[const] Real Constant 'X1p'
      X1p = 0.00031388

! 130:[const] Real Constant 'MVA_LD'
      MVA_LD = 300.0

! 140:[const] Real Constant 'LLa'
      LLa = 31600.0

! 150:[const] Real Constant 'MVA_LD_TX'
      MVA_LD_TX = 450.0

! 160:[const] Real Constant 'R1p'
      R1p = 0.00015

! 190:[timerdefn]  
!  Timer
      IF(TIME.GE.1.3)THEN
        tbgo = 1
      ELSE
        tbgo = 0
      END IF
!

! 200:[timerdefn]  
!  Timer
      IF(TIME.GE.1.1)THEN
        mcsw = 1
      ELSE
        mcsw = 0
      END IF
!

! 210:[const] Real Constant 
      RT_18 = 0.05

! 220:[const] Real Constant 
      RT_26 = 0.01

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_27 = PI2_BY3

! 240:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         BINJ = 1
      ELSE
         BINJ = 1
         IF ( TIME .GE. 7.0 ) BINJ = (1-1)
      ENDIF

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_21 = TWO_PI

! 260:[inv] Interpolated Logic Inverter 
      IF (BINJ .NE. 0) THEN
         NBINJ = 0
      ELSE
         NBINJ = 1
      ENDIF

! 270:[mult] Multiplier 
      RT_20 = RT_21 * fnom

! 280:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_20
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      ang_sys = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1.0e+308, 1.0e+30&
     &8, RVD2_2, RVD2_1)

! 290:[emtconst] Commonly Used Constants (pi...) 
      RT_33 = PI2_BY3

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_23 = TWO_PI

! 310:[const] Real Constant 'f_osc'
      RT_24 = 7.9

! 320:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT1_EXE( (IBRCH(1)+7), (IBRCH(1)+8), (IBRCH(1)+9),SS(1),1.0&
     &,0)

! 360:[div] Divider 
      IF (ABS(MVA_GEN) .LT. 1.0E-100) THEN
         IF (MVA_GEN .LT. 0.0)  THEN
            RT_34 = -1.0E100 * PH_low
         ELSE
            RT_34 =  1.0E100 * PH_low
         ENDIF
      ELSE
         RT_34 = PH_low / MVA_GEN
      ENDIF

! 370:[pu_bases] Per-unit base calculator 
      CALL pu_basesDyn(VLL_TX, MVA_GEN, fnom, Znom, RT_1, RT_2, RT_3, RT&
     &_4, RT_5, RT_6, RT_7, RT_8, RT_9)


! 380:[mult] Multiplier 
      RT_14 = ZH_pu * Znom

! 390:[div] Divider 
      IF (ABS(X1p) .LT. 1.0E-100) THEN
         IF (X1p .LT. 0.0)  THEN
            LH = -1.0E100 * RT_14
         ELSE
            LH =  1.0E100 * RT_14
         ENDIF
      ELSE
         LH = RT_14 / X1p
      ENDIF

! 400:[mult] Multiplier 
      RT_15 = ZL_pu * Znom

! 410:[div] Divider 
      IF (ABS(X1p) .LT. 1.0E-100) THEN
         IF (X1p .LT. 0.0)  THEN
            LL = -1.0E100 * RT_15
         ELSE
            LL =  1.0E100 * RT_15
         ENDIF
      ELSE
         LL = RT_15 / X1p
      ENDIF

! 420:[trig] Trigonometric Functions 
!  Trig-Func
      RT_29 = SIN(ang_sys)
!

! 430:[sumjct] Summing/Differencing Junctions 
      RT_28 = + ang_sys - RT_27

! 440:[trig] Trigonometric Functions 
!  Trig-Func
      RT_30 = SIN(RT_28)
!

! 450:[sumjct] Summing/Differencing Junctions 
      RT_32 = + ang_sys + RT_33

! 460:[trig] Trigonometric Functions 
!  Trig-Func
      RT_31 = SIN(RT_32)
!

! 470:[mult] Multiplier 
      RT_22 = RT_23 * RT_24

! 480:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_22
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      ang_osc = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1.0e+308, 1.0e+30&
     &8, RVD2_2, RVD2_1)

! 490:[mult] Multiplier 
      RT_13 = ZG_pu * Znom

! 500:[trig] Trigonometric Functions 
!  Trig-Func
      RT_25 = COS(ang_osc)
!

! 510:[multimass2] Torsional Shaft Model  
      IVD1_1 = NRTCF
      IVD1_2 = NSTORF - 1 + 2
      IVD1_3 = IVD1_2 + 2
      IVD1_4 = IVD1_2 + 8*2
      CALL MMASS2_EXE(tbgo, telec,Tmstdy, Testdy, 1.0, w,RVD1_1)
       RT_12 = RVD1_1
      torq12 = STORF(IVD1_4+1)
      blade_pos = STORF(IVD1_2+1)
      torq23 = 0.0
      abtorq = 0.0
      torq45 = 0.0
      gxtorq = 0.0
!

! 520:[sandhdefn] Sample and Hold 
!  Sample and Hold
      CALL SANDH2(RT_12,tbgo,  1,  aplt)

! 530:[sync_machine] Synchronous Machine 'Hydro'
      CALL COMPONENT_ID(ICALL_NO,1976029421)
! RVD1_1 - Speed
! RVD1_2 - Neutral Voltage
! RVD1_3 - Neutral Current
! RVD1_4 - Load Angle
! RVD1_5 - Rotor Mechanical Angle
! RVD1_6 - Real Power output
! RVD1_7 - Reactive Power output
! RVD1_8 - Mechanical Torque
! RVD1_9 - Electrical Torque
! RVD1_10:15 - Monitored STOR locations
! RVD1_16:17 - Terminal Voltage RMS,pu
! RVD1_18 - Inverse of Base MVA
! IVD1_2 - Machine is active, Initialize exciter
! IVD1_3 - Torque driven, Initialize governor/turbine
      STORI(NSTORI) = NINT(STOR(NEXC+294))
      IVD1_1 = NRTCF
      RVD1_1 = w
      IF (tbgo .EQ. 0) RVD1_1 = RTCF(IVD1_1+2)
      CALL SYNCMC3P2_EXE(SS(1),  (IBRCH(1)+67), (IBRCH(1)+68), (IBRCH(1)&
     &+69), (IBRCH(1)+70), (IBRCH(1)+71), (IBRCH(1)+72),0.0,0,mcsw,1.0,0&
     &,0,RVD1_1,aplt,0,0,1.0,0.0,376.99111843,Ef,0,1.0,0,If,RVD1_2,RVD1_&
     &3,RVD1_4,RVD1_5,RT_10,telec,RVD1_6,RVD1_7,RVD1_8,RVD1_9,IVD1_2,IVD&
     &1_3,RVD1_10,RVD1_11,RVD1_12,RVD1_13,RVD1_14,RVD1_15)
      Tmstdy = aplt
      IF ((IVD1_2 .EQ. 1) .AND. (tbgo .EQ. 1)) IVD1_3 = 1
      IF (IVD1_3 .EQ. 0) Tmstdy = RVD1_8
      Ef0 = STOR(NEXC-375+265)*STOR(NEXC-375+302)
      IF ((IVD1_2 .EQ. 1) .AND. (STORI(NSTORI).EQ.0)) THEN
          IF (STOR(NEXC-375+293).GT.0.5) THEN
              STORF(NSTORF) = STOR(NEXC-375+161)
          ELSE
              STORF(NSTORF) = STOR(NEXC-375+296)
          ENDIF
      ENDIF
      IF (IVD1_2 .EQ. 1) THEN
        STORF(NSTORF+1) = STORF(NSTORF+1) + (RT_10-RTCF(IVD1_1+2))*DELT
        IF (IVD1_3 .EQ. 0) STORF(NSTORF+2) = RVD1_4
        STORF(NSTORF+3) = STORF(NSTORF) + STORF(NSTORF+1) + STORF(NSTORF&
     &+2)
      ELSE
        STORF(NSTORF+3) = 0.0
      ENDIF
      RVD1_16 = VM3PH2(SS(1),NT_10(1),NT_10(2),NT_10(3),0.02)/(SQRT_3*RT&
     &CF(IVD1_1+1))
      IF(RVD1_16 .LT. 1.0E-8) THEN
         RVD1_17 = 1.0
      ELSE
         RVD1_17 = RVD1_16
      ENDIF
      RVD1_18 = 1.0/(3.0*RTCF(IVD1_1)*RTCF(IVD1_1+1))
      RT_11(1) = RVD1_17
      IF(RVD1_16 .LT. 1.0E-8) THEN
         RT_11(2) = 0.0
         RT_11(3) = 0.0
      ELSE
         RT_11(2) = RVD1_6*RVD1_18/RVD1_17
         RT_11(3) = -RVD1_7*RVD1_18/RVD1_17
      ENDIF
      Pout = RVD1_6/(3.0*RTCF(IVD1_1)*RTCF(IVD1_1+1))
      Qout = RVD1_7/(3.0*RTCF(IVD1_1)*RTCF(IVD1_1+1))
      Testdy = RVD1_9
      InitGv = IVD1_3
      Mactiv = IVD1_2
      NSTORF = NSTORF + 4
      NSTORI = NSTORI + 1

! 540:[sandhdefn] Sample and Hold 
!  Sample and Hold
      CALL SANDH2(RT_17,Mactiv,  1,  RT_16)

! 550:[excac] Type AC exciter 
      CALL COMPONENT_ID(ICALL_NO,665959183)
! AC Exciter Model AC1A
      CALL EXCAC1A2_EXE(RT_16,RT_11,0.0,If,Ef0,Mactiv,Ef,-1.0E10,1.0E10)
      RT_17 = STORF(THIS+3)

! 560:[mult] Multiplier 
      RT_19 = RT_26 * RT_25

! 570:[sumjct] Summing/Differencing Junctions 
      inj_mag = + RT_18 + RT_19

! 580:[mult] Multiplier 
      injB = RT_30 * inj_mag

! 590:[mult] Multiplier 
      injA = RT_29 * inj_mag

! 600:[div] Divider 
      IF (ABS(X1p) .LT. 1.0E-100) THEN
         IF (X1p .LT. 0.0)  THEN
            LG = -1.0E100 * RT_13
         ELSE
            LG =  1.0E100 * RT_13
         ENDIF
      ELSE
         LG = RT_13 / X1p
      ENDIF

! 610:[mult] Multiplier 
      injC = RT_31 * inj_mag

! 620:[datamerge] Merges data signals into an array 
      inj(1) = injA
      inj(2) = injB
      inj(3) = injC

! 630:[pgb] Output Channel 'inj'

      DO IVD1_1 = 1, 3
         PGB(IPGB+5+IVD1_1-1) = inj(IVD1_1)
      ENDDO

! 730:[pgb] Output Channel 'Machine Current,B,out+'

      PGB(IPGB+23) = 0.03567 * IMACB

! 750:[pgb] Output Channel 'Gen to Exc torque'

      PGB(IPGB+27) = gxtorq

! 770:[pgb] Output Channel 'Turbine Blade Displacement'

      PGB(IPGB+31) = 57.2957795131 * blade_pos

! 790:[pgb] Output Channel 'Machine Current,C,out+'

      PGB(IPGB+35) = 0.03567 * IMACC

! 800:[pgb] Output Channel 'Machine Current, A,out+'

      PGB(IPGB+36) = 0.03567 * IMACA

! 810:[pgb] Output Channel 'LPA to LPB torque'

      PGB(IPGB+37) = abtorq

! 820:[pgb] Output Channel 'Torque between Gen. Shaft and Turbine'

      PGB(IPGB+38) = torq12

! 830:[pgb] Output Channel 'Electrical Torque on Stator'

      PGB(IPGB+39) = telec

! 840:[pgb] Output Channel 'LL'

      PGB(IPGB+40) = LL

! 850:[pgb] Output Channel 'Znom'

      PGB(IPGB+41) = Znom

! 860:[pgb] Output Channel 'LH'

      PGB(IPGB+42) = LH

! 870:[pgb] Output Channel 'LG'

      PGB(IPGB+43) = LG

! 880:[pgb] Output Channel 'Stator Active Power, pu'

      PGB(IPGB+44) = RT_34

! 900:[source3] Three Phase Voltage Source Model 1 'SOURCE'
!  3-Phase source: SOURCE
      RVD1_1 = RTCF(NRTCF+12)
      RVD1_2 = RTCF(NRTCF+14)
      RVD1_3 = RTCF(NRTCF+13)
      CALL ESYS651_EXE(SS(1), (IBRCH(1)+16), (IBRCH(1)+17), (IBRCH(1)+18&
     &),0,0,0, SS(1), NT_4(1),NT_4(2),NT_4(3), 0, RVD1_2, RVD1_1, 0.0, 1&
     &.0, 1.0, 1.0,RVD1_3, 1.0,0.02,0.05, 1.0,0.02,0.05, RVD1_4, RVD1_5,&
     & RVD1_6, RVD1_7)

! 910:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT1_EXE( (IBRCH(1)+25), (IBRCH(1)+26), (IBRCH(1)+27),SS(1),&
     &1.0,0)

! 940:[pgb] Output Channel 'speed'

      PGB(IPGB+45) = 0.00265258238486 * w

! 950:[src_ccin_1] Current Source 'Source 1_1'
      CCBR( (IBRCH(1)+82),SS(1)) = injC
      IF (TIMEZERO) CCBRD( (IBRCH(1)+82),SS(1)) = injC

! 960:[src_ccin_1] Current Source 'Source 1_1'
      CCBR( (IBRCH(1)+84),SS(1)) = injB
      IF (TIMEZERO) CCBRD( (IBRCH(1)+84),SS(1)) = injB

! 970:[src_ccin_1] Current Source 'Source 1_1'
      CCBR( (IBRCH(1)+83),SS(1)) = injA
      IF (TIMEZERO) CCBRD( (IBRCH(1)+83),SS(1)) = injA

! 980:[breaker3] 3 Phase Breaker 'NBINJ'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+79),0.005,1000000.0,RTCF(NRTC&
     &F),0,NINT(1.0-REAL(NBINJ)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+80),0.005,1000000.0,RTCF(NRTC&
     &F),0,NINT(1.0-REAL(NBINJ)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+81),0.005,1000000.0,RTCF(NRTC&
     &F),0,NINT(1.0-REAL(NBINJ)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+79),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+80),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+81),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,2006978494,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,2006978494,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,2006978494,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+79),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+80),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+81),SS(1)))

! 990:[breaker3] 3 Phase Breaker 'BINJ'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+76),0.005,1000000.0,RTCF(NRTC&
     &F),0,NINT(1.0-REAL(BINJ)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+77),0.005,1000000.0,RTCF(NRTC&
     &F),0,NINT(1.0-REAL(BINJ)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+78),0.005,1000000.0,RTCF(NRTC&
     &F),0,NINT(1.0-REAL(BINJ)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+76),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+77),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+78),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1598872666,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1598872666,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1598872666,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+76),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+77),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+78),SS(1)))

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 2) = VLL_TX
      STOF(ISTOF + 3) = RT_1
      STOF(ISTOF + 4) = RT_2
      STOF(ISTOF + 5) = RT_3
      STOF(ISTOF + 6) = RT_4
      STOF(ISTOF + 7) = RT_5
      STOF(ISTOF + 8) = RT_6
      STOF(ISTOF + 9) = RT_7
      STOF(ISTOF + 10) = RT_8
      STOF(ISTOF + 11) = RT_9
      STOF(ISTOF + 12) = gxtorq
      STOF(ISTOF + 13) = abtorq
      STOF(ISTOF + 14) = IMACA
      STOF(ISTOF + 15) = IMACB
      STOF(ISTOF + 16) = IMACC
      STOF(ISTOF + 17) = linev
      STOI(ISTOI + 1) = mcsw
      STOF(ISTOF + 21) = torq12
      STOF(ISTOF + 22) = telec
      STOF(ISTOF + 23) = RT_10
      STOF(ISTOF + 24) = Tmstdy
      STOF(ISTOF + 25) = Ef0
      STOF(ISTOF + 29) = If
      STOF(ISTOF + 30) = Ef
      STOF(ISTOF + 31) = aplt
      STOF(ISTOF + 32) = w
      STOF(ISTOF + 33) = RT_12
      STOI(ISTOI + 2) = tbgo
      STOF(ISTOF + 34) = Testdy
      STOF(ISTOF + 35) = MVA_GEN_TX
      STOF(ISTOF + 36) = MVA_LD
      STOF(ISTOF + 37) = MVA_LD_TX
      STOF(ISTOF + 38) = RT_13
      STOF(ISTOF + 39) = ZG_pu
      STOF(ISTOF + 40) = LG
      STOF(ISTOF + 41) = LGa
      STOF(ISTOF + 42) = LHa
      STOF(ISTOF + 43) = LLa
      STOF(ISTOF + 44) = RT_14
      STOF(ISTOF + 45) = ZH_pu
      STOF(ISTOF + 46) = LH
      STOF(ISTOF + 47) = RT_15
      STOF(ISTOF + 48) = ZL_pu
      STOF(ISTOF + 49) = Znom
      STOF(ISTOF + 50) = LL
      STOF(ISTOF + 51) = X1p
      STOF(ISTOF + 52) = RT_16
      STOF(ISTOF + 53) = RT_17
      STOI(ISTOI + 3) = Mactiv
      STOF(ISTOF + 54) = R1p
      STOF(ISTOF + 61) = PH
      STOF(ISTOF + 62) = QH
      STOF(ISTOF + 63) = QG
      STOF(ISTOF + 70) = PG
      STOF(ISTOF + 77) = PL
      STOF(ISTOF + 78) = QL
      STOF(ISTOF + 79) = blade_pos
      STOI(ISTOI + 4) = BINJ
      STOI(ISTOI + 5) = NBINJ
      STOF(ISTOF + 80) = RT_18
      STOF(ISTOF + 81) = RT_19
      STOF(ISTOF + 82) = RT_20
      STOF(ISTOF + 83) = RT_21
      STOF(ISTOF + 84) = fnom
      STOF(ISTOF + 85) = RT_22
      STOF(ISTOF + 86) = RT_23
      STOF(ISTOF + 87) = RT_24
      STOF(ISTOF + 88) = RT_25
      STOF(ISTOF + 89) = ang_osc
      STOF(ISTOF + 90) = RT_26
      STOF(ISTOF + 91) = RT_27
      STOF(ISTOF + 92) = RT_28
      STOF(ISTOF + 93) = RT_29
      STOF(ISTOF + 94) = RT_30
      STOF(ISTOF + 95) = RT_31
      STOF(ISTOF + 96) = RT_32
      STOF(ISTOF + 97) = ang_sys
      STOF(ISTOF + 98) = RT_33
      STOF(ISTOF + 99) = injA
      STOF(ISTOF + 100) = injB
      STOF(ISTOF + 101) = injC
      STOF(ISTOF + 102) = inj_mag
      STOF(ISTOF + 106) = RT_34
      STOF(ISTOF + 107) = PH_low
      STOF(ISTOF + 108) = MVA_GEN
      STOF(ISTOF + 112) = Irms
      STOF(ISTOF + 113) = VMH
      STOF(ISTOF + 114) = VML
      STOF(ISTOF + 115) = Pout
      STOF(ISTOF + 116) = Qout
      STOI(ISTOI + 6) = InitGv
      STOF(ISTOF + 117) = torq23
      STOF(ISTOF + 118) = torq45
      STOF(ISTOF + 119) = VMG

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 17 + IT_0) = VMAC(IT_0)
         STOF(ISTOF + 25 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 54 + IT_0) = VH(IT_0)
         STOF(ISTOF + 57 + IT_0) = IH(IT_0)
         STOF(ISTOF + 63 + IT_0) = VG(IT_0)
         STOF(ISTOF + 66 + IT_0) = IG(IT_0)
         STOF(ISTOF + 70 + IT_0) = VL(IT_0)
         STOF(ISTOF + 73 + IT_0) = IL(IT_0)
         STOF(ISTOF + 102 + IT_0) = inj(IT_0)
         STOF(ISTOF + 108 + IT_0) = Iinst(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    P3PH3         ! 
      REAL    VM3PH2        ! '3 Phase RMS Voltage Measurement'
      REAL    RMS3PH        ! '3 Phase RMS Measurement'
      REAL    REALPOLE      ! 
!     SUBR    load_ai_trainOut  ! Variable AI Training Load
      REAL    Q3PH3         ! 
!     SUBR    pu_basesOut   ! Per-unit base calculator
      REAL    VBRANCH       ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_2(3), NT_4(3), NT_9(3)
      INTEGER  NT_10(3)

! Control Signals
      REAL     VLL_TX, IMACA, IMACB, IMACC, linev
      REAL     VMAC(3), MVA_GEN_TX, MVA_LD
      REAL     MVA_LD_TX, ZG_pu, LGa, LHa, LLa
      REAL     ZH_pu, ZL_pu, X1p, R1p, VH(3)
      REAL     IH(3), PH, QH, QG, VG(3), IG(3)
      REAL     PG, VL(3), IL(3), PL, QL, RT_18
      REAL     RT_21, fnom, RT_23, RT_24, RT_26
      REAL     RT_27, RT_33, PH_low, MVA_GEN
      REAL     Iinst(3), Irms, VMH, VML, VMG

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 45
      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 87

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      VLL_TX   = STOF(ISTOF + 2)
      IMACA    = STOF(ISTOF + 14)
      IMACB    = STOF(ISTOF + 15)
      IMACC    = STOF(ISTOF + 16)
      linev    = STOF(ISTOF + 17)
      MVA_GEN_TX = STOF(ISTOF + 35)
      MVA_LD   = STOF(ISTOF + 36)
      MVA_LD_TX = STOF(ISTOF + 37)
      ZG_pu    = STOF(ISTOF + 39)
      LGa      = STOF(ISTOF + 41)
      LHa      = STOF(ISTOF + 42)
      LLa      = STOF(ISTOF + 43)
      ZH_pu    = STOF(ISTOF + 45)
      ZL_pu    = STOF(ISTOF + 48)
      X1p      = STOF(ISTOF + 51)
      R1p      = STOF(ISTOF + 54)
      PH       = STOF(ISTOF + 61)
      QH       = STOF(ISTOF + 62)
      QG       = STOF(ISTOF + 63)
      PG       = STOF(ISTOF + 70)
      PL       = STOF(ISTOF + 77)
      QL       = STOF(ISTOF + 78)
      RT_18    = STOF(ISTOF + 80)
      RT_21    = STOF(ISTOF + 83)
      fnom     = STOF(ISTOF + 84)
      RT_23    = STOF(ISTOF + 86)
      RT_24    = STOF(ISTOF + 87)
      RT_26    = STOF(ISTOF + 90)
      RT_27    = STOF(ISTOF + 91)
      RT_33    = STOF(ISTOF + 98)
      PH_low   = STOF(ISTOF + 107)
      MVA_GEN  = STOF(ISTOF + 108)
      Irms     = STOF(ISTOF + 112)
      VMH      = STOF(ISTOF + 113)
      VML      = STOF(ISTOF + 114)
      VMG      = STOF(ISTOF + 119)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         VMAC(IT_0) = STOF(ISTOF + 17 + IT_0)
         VH(IT_0) = STOF(ISTOF + 54 + IT_0)
         IH(IT_0) = STOF(ISTOF + 57 + IT_0)
         VG(IT_0) = STOF(ISTOF + 63 + IT_0)
         IG(IT_0) = STOF(ISTOF + 66 + IT_0)
         VL(IT_0) = STOF(ISTOF + 70 + IT_0)
         IL(IT_0) = STOF(ISTOF + 73 + IT_0)
         Iinst(IT_0) = STOF(ISTOF + 108 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_2(IT_0) = NODE(INODE + 3 + IT_0)
         NT_4(IT_0) = NODE(INODE + 9 + IT_0)
         NT_9(IT_0) = NODE(INODE + 24 + IT_0)
         NT_10(IT_0) = NODE(INODE + 27 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Iinst(1) = ( CBR((IBRCH(1)+10), SS(1)))
      Iinst(2) = ( CBR((IBRCH(1)+11), SS(1)))
      Iinst(3) = ( CBR((IBRCH(1)+12), SS(1)))
      VMAC(1) = EMTDC_VVDC(SS(1), NT_10(1), 0)
      VMAC(2) = EMTDC_VVDC(SS(1), NT_10(2), 0)
      VMAC(3) = EMTDC_VVDC(SS(1), NT_10(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+10), (IBRCH(1)+11),&
     & (IBRCH(1)+12),RTCF(IVD1_1+2),0)
      PH_low = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(1), NT_10(1), NT_10(2), NT_10(&
     &3), RTCF(IVD1_1+2))
      linev = RVD1_1
      RVD1_1 = RMS3PH(( CBR((IBRCH(1)+10), SS(1))),( CBR((IBRCH(1)+11), &
     &SS(1))),( CBR((IBRCH(1)+12), SS(1))))
      RVD1_1 = REALPOLE(0,1,0,RTCF(IVD1_1+4),RTCF(IVD1_1+2),RVD1_1,0.0,0&
     &.0,RTCF(IVD1_1+2))
      Irms = RVD1_1

! 20:[load_ai_train] Variable AI Training Load 
      CALL load_ai_trainOut()


! 30:[const] Real Constant 'VLL_TX'

      VLL_TX = 345.0

! 40:[const] Real Constant 'fnom'

      fnom = 60.0

! 50:[const] Real Constant 'ZG_pu'

      ZG_pu = 0.075

! 60:[const] Real Constant 'MVA_GEN'

      MVA_GEN = 60.0

! 70:[const] Real Constant 'ZH_pu'

      ZH_pu = 0.025

! 80:[const] Real Constant 'LGa'

      LGa = 94800.0

! 90:[const] Real Constant 'ZL_pu'

      ZL_pu = 0.025

! 100:[const] Real Constant 'MVA_GEN_TX'

      MVA_GEN_TX = 450.0

! 110:[const] Real Constant 'LHa'

      LHa = 31600.0

! 120:[const] Real Constant 'X1p'

      X1p = 0.00031388

! 130:[const] Real Constant 'MVA_LD'

      MVA_LD = 300.0

! 140:[const] Real Constant 'LLa'

      LLa = 31600.0

! 150:[const] Real Constant 'MVA_LD_TX'

      MVA_LD_TX = 450.0

! 160:[const] Real Constant 'R1p'

      R1p = 0.00015

! 170:[pgb] Output Channel 'Machine Volts'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = 0.0471 * VMAC(IVD1_1)
      ENDDO

! 180:[pgb] Output Channel 'Machine Output Volt'

      PGB(IPGB+4) = linev

! 210:[const] Real Constant 

      RT_18 = 0.05

! 220:[const] Real Constant 

      RT_26 = 0.01

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_27 = PI2_BY3

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_21 = TWO_PI

! 290:[emtconst] Commonly Used Constants (pi...) 
      RT_33 = PI2_BY3

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_23 = TWO_PI

! 310:[const] Real Constant 'f_osc'

      RT_24 = 7.9

! 320:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
      IMACA = CDCTR(2,(IXFMR + 1))-CDCTR(2,(IXFMR + 3))
      IMACB = CDCTR(2,(IXFMR + 2))-CDCTR(2,(IXFMR + 1))
      IMACC = CDCTR(2,(IXFMR + 3))-CDCTR(2,(IXFMR + 2))

! 330:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IH(1) = ( CBR((IBRCH(1)+13), SS(1)))
      IH(2) = ( CBR((IBRCH(1)+14), SS(1)))
      IH(3) = ( CBR((IBRCH(1)+15), SS(1)))
      VH(1) = EMTDC_VVDC(SS(1), NT_2(1), 0)
      VH(2) = EMTDC_VVDC(SS(1), NT_2(2), 0)
      VH(3) = EMTDC_VVDC(SS(1), NT_2(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+13), (IBRCH(1)+14),&
     & (IBRCH(1)+15),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1770662834,RVD1_1,"Pd")
      PH = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+13), (IBRCH(1)+14),&
     & (IBRCH(1)+15),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1770662834,RVD1_1,"Qd")
      QH = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(1), NT_2(1), NT_2(2), NT_2(3),&
     & RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1770662834,RVD1_1,"Vd")
      VMH = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1770662834,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1770662834,1,"hide2")
      ENDIF

! 340:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IL(1) = ( CBR((IBRCH(1)+52), SS(1)))
      IL(2) = ( CBR((IBRCH(1)+53), SS(1)))
      IL(3) = ( CBR((IBRCH(1)+54), SS(1)))
      VL(1) = EMTDC_VVDC(SS(1), NT_9(1), 0)
      VL(2) = EMTDC_VVDC(SS(1), NT_9(2), 0)
      VL(3) = EMTDC_VVDC(SS(1), NT_9(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+52), (IBRCH(1)+53),&
     & (IBRCH(1)+54),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,466886239,RVD1_1,"Pd")
      PL = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+52), (IBRCH(1)+53),&
     & (IBRCH(1)+54),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,466886239,RVD1_1,"Qd")
      QL = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(1), NT_9(1), NT_9(2), NT_9(3),&
     & RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,466886239,RVD1_1,"Vd")
      VML = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,466886239,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,466886239,1,"hide2")
      ENDIF

! 350:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IG(1) = ( CBR((IBRCH(1)+73), SS(1)))
      IG(2) = ( CBR((IBRCH(1)+74), SS(1)))
      IG(3) = ( CBR((IBRCH(1)+75), SS(1)))
      VG(1) = EMTDC_VVDC(SS(1), NT_4(1), 0)
      VG(2) = EMTDC_VVDC(SS(1), NT_4(2), 0)
      VG(3) = EMTDC_VVDC(SS(1), NT_4(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+73), (IBRCH(1)+74),&
     & (IBRCH(1)+75),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1496692289,RVD1_1,"Pd")
      PG = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+73), (IBRCH(1)+74),&
     & (IBRCH(1)+75),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1496692289,RVD1_1,"Qd")
      QG = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(1), NT_4(1), NT_4(2), NT_4(3),&
     & RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1496692289,RVD1_1,"Vd")
      VMG = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1496692289,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1496692289,1,"hide2")
      ENDIF

! 370:[pu_bases] Per-unit base calculator 
      CALL pu_basesOut()


! 640:[pgb] Output Channel 'QL'

      PGB(IPGB+8) = QL

! 650:[pgb] Output Channel 'QG'

      PGB(IPGB+9) = QG

! 660:[pgb] Output Channel 'QH'

      PGB(IPGB+10) = QH

! 670:[pgb] Output Channel 'PL'

      PGB(IPGB+11) = PL

! 680:[pgb] Output Channel 'PG'

      PGB(IPGB+12) = PG

! 690:[pgb] Output Channel 'PH'

      PGB(IPGB+13) = PH

! 700:[pgb] Output Channel 'IL'

      DO IVD1_1 = 1, 3
         PGB(IPGB+14+IVD1_1-1) = IL(IVD1_1)
      ENDDO

! 710:[pgb] Output Channel 'IG'

      DO IVD1_1 = 1, 3
         PGB(IPGB+17+IVD1_1-1) = IG(IVD1_1)
      ENDDO

! 720:[pgb] Output Channel 'IH'

      DO IVD1_1 = 1, 3
         PGB(IPGB+20+IVD1_1-1) = IH(IVD1_1)
      ENDDO

! 740:[pgb] Output Channel 'VL'

      DO IVD1_1 = 1, 3
         PGB(IPGB+24+IVD1_1-1) = VL(IVD1_1)
      ENDDO

! 760:[pgb] Output Channel 'VG'

      DO IVD1_1 = 1, 3
         PGB(IPGB+28+IVD1_1-1) = VG(IVD1_1)
      ENDDO

! 780:[pgb] Output Channel 'VH'

      DO IVD1_1 = 1, 3
         PGB(IPGB+32+IVD1_1-1) = VH(IVD1_1)
      ENDDO

! 980:[breaker3] 3 Phase Breaker 'NBINJ'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+79), (IBRCH(1)+80), (IBRCH(1)+81),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 990:[breaker3] 3 Phase Breaker 'BINJ'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+76), (IBRCH(1)+77), (IBRCH(1)+78),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 2) = VLL_TX
      STOF(ISTOF + 14) = IMACA
      STOF(ISTOF + 15) = IMACB
      STOF(ISTOF + 16) = IMACC
      STOF(ISTOF + 17) = linev
      STOF(ISTOF + 35) = MVA_GEN_TX
      STOF(ISTOF + 36) = MVA_LD
      STOF(ISTOF + 37) = MVA_LD_TX
      STOF(ISTOF + 39) = ZG_pu
      STOF(ISTOF + 41) = LGa
      STOF(ISTOF + 42) = LHa
      STOF(ISTOF + 43) = LLa
      STOF(ISTOF + 45) = ZH_pu
      STOF(ISTOF + 48) = ZL_pu
      STOF(ISTOF + 51) = X1p
      STOF(ISTOF + 54) = R1p
      STOF(ISTOF + 61) = PH
      STOF(ISTOF + 62) = QH
      STOF(ISTOF + 63) = QG
      STOF(ISTOF + 70) = PG
      STOF(ISTOF + 77) = PL
      STOF(ISTOF + 78) = QL
      STOF(ISTOF + 80) = RT_18
      STOF(ISTOF + 83) = RT_21
      STOF(ISTOF + 84) = fnom
      STOF(ISTOF + 86) = RT_23
      STOF(ISTOF + 87) = RT_24
      STOF(ISTOF + 90) = RT_26
      STOF(ISTOF + 91) = RT_27
      STOF(ISTOF + 98) = RT_33
      STOF(ISTOF + 107) = PH_low
      STOF(ISTOF + 108) = MVA_GEN
      STOF(ISTOF + 112) = Irms
      STOF(ISTOF + 113) = VMH
      STOF(ISTOF + 114) = VML
      STOF(ISTOF + 119) = VMG

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 17 + IT_0) = VMAC(IT_0)
         STOF(ISTOF + 54 + IT_0) = VH(IT_0)
         STOF(ISTOF + 57 + IT_0) = IH(IT_0)
         STOF(ISTOF + 63 + IT_0) = VG(IT_0)
         STOF(ISTOF + 66 + IT_0) = IG(IT_0)
         STOF(ISTOF + 70 + IT_0) = VL(IT_0)
         STOF(ISTOF + 73 + IT_0) = IL(IT_0)
         STOF(ISTOF + 108 + IT_0) = Iinst(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin(f)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    load_ai_trainDyn_Begin  ! Variable AI Training Load
!     SUBR    pu_basesDyn_Begin  ! Per-unit base calculator

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: f

! Electrical Node Indices

! Control Signals
      REAL     VLL_TX, MVA_GEN_TX, MVA_LD
      REAL     MVA_LD_TX, ZG_pu, LGa, LHa, LLa
      REAL     ZH_pu, ZL_pu, X1p, R1p, RT_18
      REAL     RT_21, fnom, RT_23, RT_24, RT_26
      REAL     RT_27, RT_33, MVA_GEN

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      INTEGER  IVD1_5, IVD1_6
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6, RVD10_1(10)
      REAL     RVD10_2(10)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 87

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[load_ai_train] Variable AI Training Load 
      CALL load_ai_trainDyn_Begin(0.001, 2.0)


! 30:[const] Real Constant 'VLL_TX'
      VLL_TX = 345.0

! 40:[const] Real Constant 'fnom'
      fnom = 60.0

! 50:[const] Real Constant 'ZG_pu'
      ZG_pu = 0.075

! 60:[const] Real Constant 'MVA_GEN'
      MVA_GEN = 60.0

! 70:[const] Real Constant 'ZH_pu'
      ZH_pu = 0.025

! 80:[const] Real Constant 'LGa'
      LGa = 94800.0

! 90:[const] Real Constant 'ZL_pu'
      ZL_pu = 0.025

! 100:[const] Real Constant 'MVA_GEN_TX'
      MVA_GEN_TX = 450.0

! 110:[const] Real Constant 'LHa'
      LHa = 31600.0

! 120:[const] Real Constant 'X1p'
      X1p = 0.00031388

! 130:[const] Real Constant 'MVA_LD'
      MVA_LD = 300.0

! 140:[const] Real Constant 'LLa'
      LLa = 31600.0

! 150:[const] Real Constant 'MVA_LD_TX'
      MVA_LD_TX = 450.0

! 160:[const] Real Constant 'R1p'
      R1p = 0.00015

! 190:[timerdefn]  

! 200:[timerdefn]  

! 210:[const] Real Constant 
      RT_18 = 0.05

! 220:[const] Real Constant 
      RT_26 = 0.01

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_27 = PI2_BY3

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_21 = TWO_PI

! 260:[inv] Interpolated Logic Inverter 

! 270:[mult] Multiplier 

! 280:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 290:[emtconst] Commonly Used Constants (pi...) 
      RT_33 = PI2_BY3

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_23 = TWO_PI

! 310:[const] Real Constant 'f_osc'
      RT_24 = 7.9

! 320:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,2075573788)
      RVD1_1 = ONE_3RD*MVA_GEN_TX
      RVD1_2 = VLL_TX*SQRT_1BY3
      RVD1_3 = 18.0
      CALL E_TF2W_CFG((IXFMR + 1),1,RVD1_1,60.0,0.1,0.01,RVD1_2,RVD1_3,1&
     &.0)
      CALL E_TF2W_CFG((IXFMR + 2),1,RVD1_1,60.0,0.1,0.01,RVD1_2,RVD1_3,1&
     &.0)
      CALL E_TF2W_CFG((IXFMR + 3),1,RVD1_1,60.0,0.1,0.01,RVD1_2,RVD1_3,1&
     &.0)
      IF (0.0 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0
        RVD1_4 = 6.0/(MVA_GEN_TX*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH(1)+1),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+2),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+3),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+4),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+5),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+6),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT1_CFG( (IBRCH(1)+7), (IBRCH(1)+8), (IBRCH(1)+9),SS(1),RVD&
     &1_1,RVD1_2,0.2,1.25,60.0,1.0,1.0,0.0)

! 360:[div] Divider 

! 370:[pu_bases] Per-unit base calculator 
      CALL pu_basesDyn_Begin()


! 380:[mult] Multiplier 

! 390:[div] Divider 

! 400:[mult] Multiplier 

! 410:[div] Divider 

! 420:[trig] Trigonometric Functions 

! 430:[sumjct] Summing/Differencing Junctions 

! 440:[trig] Trigonometric Functions 

! 450:[sumjct] Summing/Differencing Junctions 

! 460:[trig] Trigonometric Functions 

! 470:[mult] Multiplier 

! 480:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 490:[mult] Multiplier 

! 500:[trig] Trigonometric Functions 

! 510:[multimass2] Torsional Shaft Model  
      IVD1_1 = NRTCF
      IVD1_2 = IVD1_1 + 3   ! H
      IVD1_3 = IVD1_2 + 2   ! K
      IVD1_4 = IVD1_3 + 2   ! TF
      IVD1_5 = IVD1_4 + 2   ! MD
      IVD1_6 = IVD1_5 + 2   ! SD
      RTCF(IVD1_2+1) = 90600.0
      RTCF(IVD1_2+2) = 653000.0 
      RTCF(IVD1_3+1) = 208000000.0
      RTCF(IVD1_4+1) = 1.0
      RTCF(IVD1_4+2) = 0.0
      RTCF(IVD1_5+1) = 0.0
      RTCF(IVD1_6+1) = 137000.0
      RTCF(IVD1_6+2) = 0.0 
      CALL COMPONENT_ID(ICALL_NO,1934129376)
      CALL MMASS2_CFG(2,2,10,MVA_GEN,fnom,200.0,0.0)

! 520:[sandhdefn] Sample and Hold 

! 530:[sync_machine] Synchronous Machine 'Hydro'
      CALL COMPONENT_ID(ICALL_NO,1976029421)
      RVD10_1 = 0.0
      RVD10_2 = 0.0
      RVD10_1(2) = 1.0
      RVD10_2(2) = SQRT_2/(0.946-0.111*1.0)
      RVD10_1(3) = -1.0
      CALL SYNCMC3P0_CFG(1,0,1,376.99111843,0.001, 0.111,1.0,0.946,0.19,&
     &0.26,1.0E-6, 0.565,0.23,0.228,RVD1_1,RVD1_2,RVD1_3)
      RVD1_6 = ONE_3RD*MVA_GEN/10.4
      CALL SYNCMC3P2_CFG(1,1,0,1,1,1,1,1,1,RVD1_6,10.4,376.99111843,1000&
     &0.0,0.0,1.0,0.0,300.0,RVD1_1,RVD1_2,0.946,0.19, 0.045,0.26,8.0,1.0&
     &E6,1.0E6, 0.565,0.23,0.1, 1.0E6,1.0E6, RVD10_1,RVD10_2, 1.0,-0.514&
     &872129338,0.0,0.0,0.0, 0.0,100.0,0.2,1.0,-0.514872129338,20.0,10.0&
     &)

! 540:[sandhdefn] Sample and Hold 

! 550:[excac] Type AC exciter 
      CALL COMPONENT_ID(ICALL_NO,665959183)
      CALL EXCAC1A2_CFG(0.0,0.0,100.0,0.03,14.5,-14.5,5.0,-5.0,0.1,4.18,&
     &0.03,3.14,0.8,1.0,0.38,0.2,0.03,1.0,0.0,0.0,0.0)

! 560:[mult] Multiplier 

! 570:[sumjct] Summing/Differencing Junctions 

! 580:[mult] Multiplier 

! 590:[mult] Multiplier 

! 600:[div] Divider 

! 610:[mult] Multiplier 

! 620:[datamerge] Merges data signals into an array 

! 630:[pgb] Output Channel 'inj'

! 730:[pgb] Output Channel 'Machine Current,B,out+'

! 750:[pgb] Output Channel 'Gen to Exc torque'

! 770:[pgb] Output Channel 'Turbine Blade Displacement'

! 790:[pgb] Output Channel 'Machine Current,C,out+'

! 800:[pgb] Output Channel 'Machine Current, A,out+'

! 810:[pgb] Output Channel 'LPA to LPB torque'

! 820:[pgb] Output Channel 'Torque between Gen. Shaft and Turbine'

! 830:[pgb] Output Channel 'Electrical Torque on Stator'

! 840:[pgb] Output Channel 'LL'

! 850:[pgb] Output Channel 'Znom'

! 860:[pgb] Output Channel 'LH'

! 870:[pgb] Output Channel 'LG'

! 880:[pgb] Output Channel 'Stator Active Power, pu'

! 890:[newpi] Coupled Pi Section Transmission Line 'Line1'
      CALL COMPONENT_ID(ICALL_NO,1284220206)
      CALL PI3_SECTION_CFG(1,1,0, 0.0,0.0,60.0,LGa,R1p,X1p,273.5448,0.00&
     &02952201,0.001039898,414.1642,RVD1_1,RVD1_2,RVD1_3,RVD1_4,RVD1_5,R&
     &VD1_6,IVD1_1,IVD1_2,IVD1_3,IVD1_4)
      CALL E_BRANCH_CFG( (IBRCH(1)+40),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+41),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+42),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+43),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+44),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+45),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+46),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+47),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+48),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+49),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+50),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+51),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL COUPLED_PI3_TF_CFG((IXFMR + 4),2,RVD1_1,RVD1_2,RVD1_4,RVD1_5)

! 900:[source3] Three Phase Voltage Source Model 1 'SOURCE'
      CALL COMPONENT_ID(ICALL_NO,2127421228)
      RVD1_1 = 1.0
      RVD1_2 = 0.1
      CALL ESYS651_CFG(3,1,0,0,0,SS(1), (IBRCH(1)+16), (IBRCH(1)+17), (I&
     &BRCH(1)+18),0,0,0, fnom,fnom,0.0,VLL_TX,0.0,0.0,100.0,VLL_TX, VLL_&
     &TX, 1.0,80.0,2.0, 0.001, 1.0, 0.1, 1.0,80.0,1.0,0.1)

! 910:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,2006436831)
      RVD1_1 = ONE_3RD*MVA_LD_TX
      RVD1_2 = 0.48*SQRT_1BY3
      RVD1_3 = VLL_TX
      CALL E_TF2W_CFG((IXFMR + 5),1,RVD1_1,60.0,0.06,0.0,RVD1_2,RVD1_3,1&
     &.0)
      CALL E_TF2W_CFG((IXFMR + 6),1,RVD1_1,60.0,0.06,0.0,RVD1_2,RVD1_3,1&
     &.0)
      CALL E_TF2W_CFG((IXFMR + 7),1,RVD1_1,60.0,0.06,0.0,RVD1_2,RVD1_3,1&
     &.0)
      IF (0.0 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0
        RVD1_4 = 6.0/(MVA_LD_TX*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH(1)+19),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+20),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+21),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+22),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+23),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+24),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT1_CFG( (IBRCH(1)+25), (IBRCH(1)+26), (IBRCH(1)+27),SS(1),&
     &RVD1_1,RVD1_2,0.2,1.25,60.0,1.0,1.0,0.0)

! 920:[newpi] Coupled Pi Section Transmission Line 'Line1'
      CALL COMPONENT_ID(ICALL_NO,540217533)
      CALL PI3_SECTION_CFG(1,1,0, 0.0,0.0,60.0,LLa,1.781598e-05,0.000313&
     &88,273.5448,0.0002952201,0.001039898,414.1642,RVD1_1,RVD1_2,RVD1_3&
     &,RVD1_4,RVD1_5,RVD1_6,IVD1_1,IVD1_2,IVD1_3,IVD1_4)
      CALL E_BRANCH_CFG( (IBRCH(1)+55),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+56),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+57),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+58),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+59),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+60),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+61),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+62),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+63),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+64),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+65),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+66),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL COUPLED_PI3_TF_CFG((IXFMR + 8),2,RVD1_1,RVD1_2,RVD1_4,RVD1_5)

! 930:[newpi] Coupled Pi Section Transmission Line 'Line1'
      CALL COMPONENT_ID(ICALL_NO,1990498697)
      CALL PI3_SECTION_CFG(1,1,0, 0.0,0.0,60.0,LHa,R1p,X1p,273.5448,0.00&
     &02952201,0.001039898,414.1642,RVD1_1,RVD1_2,RVD1_3,RVD1_4,RVD1_5,R&
     &VD1_6,IVD1_1,IVD1_2,IVD1_3,IVD1_4)
      CALL E_BRANCH_CFG( (IBRCH(1)+28),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+29),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+30),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+31),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+32),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+33),SS(1),0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH(1)+34),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+35),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+36),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+37),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+38),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH(1)+39),SS(1),0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL COUPLED_PI3_TF_CFG((IXFMR + 9),2,RVD1_1,RVD1_2,RVD1_4,RVD1_5)

! 940:[pgb] Output Channel 'speed'

! 950:[src_ccin_1] Current Source 'Source 1_1'
      CALL CURRENT_SOURCE2_CFG( (IBRCH(1)+82),SS(1))

! 960:[src_ccin_1] Current Source 'Source 1_1'
      CALL CURRENT_SOURCE2_CFG( (IBRCH(1)+84),SS(1))

! 970:[src_ccin_1] Current Source 'Source 1_1'
      CALL CURRENT_SOURCE2_CFG( (IBRCH(1)+83),SS(1))

! 980:[breaker3] 3 Phase Breaker 'NBINJ'
      CALL COMPONENT_ID(ICALL_NO,2006978494)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 990:[breaker3] 3 Phase Breaker 'BINJ'
      CALL COMPONENT_ID(ICALL_NO,1598872666)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin(f)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    load_ai_trainOut_Begin  ! Variable AI Training Load
!     SUBR    pu_basesOut_Begin  ! Per-unit base calculator

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: f

! Electrical Node Indices
      INTEGER  NT_2(3), NT_4(3), NT_9(3)
      INTEGER  NT_10(3)

! Control Signals
      REAL     VLL_TX, MVA_GEN_TX, MVA_LD
      REAL     MVA_LD_TX, ZG_pu, LGa, LHa, LLa
      REAL     ZH_pu, ZL_pu, X1p, R1p, RT_18
      REAL     RT_21, fnom, RT_23, RT_24, RT_26
      REAL     RT_27, RT_33, MVA_GEN

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 87

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_2(IT_0) = NODE(INODE + 3 + IT_0)
         NT_4(IT_0) = NODE(INODE + 9 + IT_0)
         NT_9(IT_0) = NODE(INODE + 24 + IT_0)
         NT_10(IT_0) = NODE(INODE + 27 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(26.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(26.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 20:[load_ai_train] Variable AI Training Load 
      CALL load_ai_trainOut_Begin(0.001, 2.0)


! 30:[const] Real Constant 'VLL_TX'
      VLL_TX = 345.0

! 40:[const] Real Constant 'fnom'
      fnom = 60.0

! 50:[const] Real Constant 'ZG_pu'
      ZG_pu = 0.075

! 60:[const] Real Constant 'MVA_GEN'
      MVA_GEN = 60.0

! 70:[const] Real Constant 'ZH_pu'
      ZH_pu = 0.025

! 80:[const] Real Constant 'LGa'
      LGa = 94800.0

! 90:[const] Real Constant 'ZL_pu'
      ZL_pu = 0.025

! 100:[const] Real Constant 'MVA_GEN_TX'
      MVA_GEN_TX = 450.0

! 110:[const] Real Constant 'LHa'
      LHa = 31600.0

! 120:[const] Real Constant 'X1p'
      X1p = 0.00031388

! 130:[const] Real Constant 'MVA_LD'
      MVA_LD = 300.0

! 140:[const] Real Constant 'LLa'
      LLa = 31600.0

! 150:[const] Real Constant 'MVA_LD_TX'
      MVA_LD_TX = 450.0

! 160:[const] Real Constant 'R1p'
      R1p = 0.00015

! 170:[pgb] Output Channel 'Machine Volts'

! 180:[pgb] Output Channel 'Machine Output Volt'

! 210:[const] Real Constant 
      RT_18 = 0.05

! 220:[const] Real Constant 
      RT_26 = 0.01

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_27 = PI2_BY3

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_21 = TWO_PI

! 290:[emtconst] Commonly Used Constants (pi...) 
      RT_33 = PI2_BY3

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_23 = TWO_PI

! 310:[const] Real Constant 'f_osc'
      RT_24 = 7.9

! 330:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(VLL_TX) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(VLL_TX)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 340:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(VLL_TX) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(VLL_TX)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 350:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(VLL_TX) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(VLL_TX)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 370:[pu_bases] Per-unit base calculator 
      CALL pu_basesOut_Begin()


! 640:[pgb] Output Channel 'QL'

! 650:[pgb] Output Channel 'QG'

! 660:[pgb] Output Channel 'QH'

! 670:[pgb] Output Channel 'PL'

! 680:[pgb] Output Channel 'PG'

! 690:[pgb] Output Channel 'PH'

! 700:[pgb] Output Channel 'IL'

! 710:[pgb] Output Channel 'IG'

! 720:[pgb] Output Channel 'IH'

! 740:[pgb] Output Channel 'VL'

! 760:[pgb] Output Channel 'VG'

! 780:[pgb] Output Channel 'VH'

      RETURN
      END

