!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : pu_bases
! Description   : Per-unit base calculator
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE pu_basesDyn(vll_rms, S_3ph, f, Z, L, C, T, w, i_rms,   &
     &   i_pk, v_ln_pk, v_ln_rms, v_ll_pk)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: vll_rms, S_3ph, f
      REAL,    INTENT(OUT) :: Z, L, C, T, w
      REAL,    INTENT(OUT) :: i_rms, i_pk
      REAL,    INTENT(OUT) :: v_ln_pk, v_ln_rms
      REAL,    INTENT(OUT) :: v_ll_pk

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11
      REAL     RT_12

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF                               ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 25
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Z        = STOF(ISTOF + 4)
      L        = STOF(ISTOF + 5)
      C        = STOF(ISTOF + 6)
      T        = STOF(ISTOF + 7)
      w        = STOF(ISTOF + 8)
      i_rms    = STOF(ISTOF + 9)
      i_pk     = STOF(ISTOF + 10)
      v_ln_pk  = STOF(ISTOF + 11)
      v_ln_rms = STOF(ISTOF + 12)
      v_ll_pk  = STOF(ISTOF + 13)
      RT_1     = STOF(ISTOF + 14)
      RT_2     = STOF(ISTOF + 15)
      RT_3     = STOF(ISTOF + 16)
      RT_4     = STOF(ISTOF + 17)
      RT_5     = STOF(ISTOF + 18)
      RT_6     = STOF(ISTOF + 19)
      RT_7     = STOF(ISTOF + 20)
      RT_8     = STOF(ISTOF + 21)
      RT_9     = STOF(ISTOF + 22)
      RT_10    = STOF(ISTOF + 23)
      RT_11    = STOF(ISTOF + 24)
      RT_12    = STOF(ISTOF + 25)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'pu_bases.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = SQRT_2

! 50:[const] Real Constant 
      RT_5 = 1.0

! 60:[div] Divider 
      IF (ABS(f) .LT. 1.0E-100) THEN
         IF (f .LT. 0.0)  THEN
            T = -1.0E100 * RT_5
         ELSE
            T =  1.0E100 * RT_5
         ENDIF
      ELSE
         T = RT_5 / f
      ENDIF

! 70:[mult] Multiplier 
      v_ll_pk = vll_rms * RT_4

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_3 = SQRT_1BY3

! 110:[mult] Multiplier 
      v_ln_rms = RT_3 * vll_rms

! 130:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = SQRT_2

! 140:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

! 150:[mult] Multiplier 
      w = RT_1 * f

! 160:[mult] Multiplier 
      v_ln_pk = RT_2 * v_ln_rms

! 190:[div] Divider 
      IF (ABS(vll_rms) .LT. 1.0E-100) THEN
         IF (vll_rms .LT. 0.0)  THEN
            RT_6 = -1.0E100 * S_3ph
         ELSE
            RT_6 =  1.0E100 * S_3ph
         ENDIF
      ELSE
         RT_6 = S_3ph / vll_rms
      ENDIF

! 200:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = SQRT_1BY3

! 210:[emtconst] Commonly Used Constants (pi...) 
      RT_8 = SQRT_2

! 220:[square] Square 
      RT_9 = vll_rms * vll_rms

! 230:[div] Divider 
      IF (ABS(S_3ph) .LT. 1.0E-100) THEN
         IF (S_3ph .LT. 0.0)  THEN
            Z = -1.0E100 * RT_9
         ELSE
            Z =  1.0E100 * RT_9
         ENDIF
      ELSE
         Z = RT_9 / S_3ph
      ENDIF

! 250:[div] Divider 
      IF (ABS(w) .LT. 1.0E-100) THEN
         IF (w .LT. 0.0)  THEN
            L = -1.0E100 * Z
         ELSE
            L =  1.0E100 * Z
         ENDIF
      ELSE
         L = Z / w
      ENDIF

! 270:[mult] Multiplier 
      RT_12 = Z * w

! 280:[const] Real Constant 
      RT_11 = 1.0

! 290:[div] Divider 
      IF (ABS(RT_12) .LT. 1.0E-100) THEN
         IF (RT_12 .LT. 0.0)  THEN
            RT_10 = -1.0E100 * RT_11
         ELSE
            RT_10 =  1.0E100 * RT_11
         ENDIF
      ELSE
         RT_10 = RT_11 / RT_12
      ENDIF

! 300:[gain] Gain Block 
!  Gain
      C = 1000000.0 * RT_10

! 320:[mult] Multiplier 
      i_rms = RT_6 * RT_7

! 330:[mult] Multiplier 
      i_pk = RT_8 * i_rms

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = vll_rms
      STOF(ISTOF + 2) = S_3ph
      STOF(ISTOF + 3) = f
      STOF(ISTOF + 4) = Z
      STOF(ISTOF + 5) = L
      STOF(ISTOF + 6) = C
      STOF(ISTOF + 7) = T
      STOF(ISTOF + 8) = w
      STOF(ISTOF + 9) = i_rms
      STOF(ISTOF + 10) = i_pk
      STOF(ISTOF + 11) = v_ln_pk
      STOF(ISTOF + 12) = v_ln_rms
      STOF(ISTOF + 13) = v_ll_pk
      STOF(ISTOF + 14) = RT_1
      STOF(ISTOF + 15) = RT_2
      STOF(ISTOF + 16) = RT_3
      STOF(ISTOF + 17) = RT_4
      STOF(ISTOF + 18) = RT_5
      STOF(ISTOF + 19) = RT_6
      STOF(ISTOF + 20) = RT_7
      STOF(ISTOF + 21) = RT_8
      STOF(ISTOF + 22) = RT_9
      STOF(ISTOF + 23) = RT_10
      STOF(ISTOF + 24) = RT_11
      STOF(ISTOF + 25) = RT_12


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Z        is output
      !L        is output
      !C        is output
      !T        is output
      !w        is output
      !i_rms    is output
      !i_pk     is output
      !v_ln_pk  is output
      !v_ln_rms is output
      !v_ll_pk  is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE pu_basesOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_7
      REAL     RT_8, RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 14)
      RT_2     = STOF(ISTOF + 15)
      RT_3     = STOF(ISTOF + 16)
      RT_4     = STOF(ISTOF + 17)
      RT_5     = STOF(ISTOF + 18)
      RT_7     = STOF(ISTOF + 20)
      RT_8     = STOF(ISTOF + 21)
      RT_11    = STOF(ISTOF + 24)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'pu_bases.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = SQRT_2

! 50:[const] Real Constant 

      RT_5 = 1.0

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_3 = SQRT_1BY3

! 130:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = SQRT_2

! 140:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

! 200:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = SQRT_1BY3

! 210:[emtconst] Commonly Used Constants (pi...) 
      RT_8 = SQRT_2

! 280:[const] Real Constant 

      RT_11 = 1.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 14) = RT_1
      STOF(ISTOF + 15) = RT_2
      STOF(ISTOF + 16) = RT_3
      STOF(ISTOF + 17) = RT_4
      STOF(ISTOF + 18) = RT_5
      STOF(ISTOF + 20) = RT_7
      STOF(ISTOF + 21) = RT_8
      STOF(ISTOF + 24) = RT_11


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE pu_basesDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_7
      REAL     RT_8, RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = SQRT_2

! 50:[const] Real Constant 
      RT_5 = 1.0

! 60:[div] Divider 

! 70:[mult] Multiplier 

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_3 = SQRT_1BY3

! 110:[mult] Multiplier 

! 130:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = SQRT_2

! 140:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

! 150:[mult] Multiplier 

! 160:[mult] Multiplier 

! 190:[div] Divider 

! 200:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = SQRT_1BY3

! 210:[emtconst] Commonly Used Constants (pi...) 
      RT_8 = SQRT_2

! 220:[square] Square 

! 230:[div] Divider 

! 250:[div] Divider 

! 270:[mult] Multiplier 

! 280:[const] Real Constant 
      RT_11 = 1.0

! 290:[div] Divider 

! 300:[gain] Gain Block 

! 320:[mult] Multiplier 

! 330:[mult] Multiplier 

      RETURN
      END

!=======================================================================

      SUBROUTINE pu_basesOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_7
      REAL     RT_8, RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = SQRT_2

! 50:[const] Real Constant 
      RT_5 = 1.0

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_3 = SQRT_1BY3

! 130:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = SQRT_2

! 140:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = TWO_PI

! 200:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = SQRT_1BY3

! 210:[emtconst] Commonly Used Constants (pi...) 
      RT_8 = SQRT_2

! 280:[const] Real Constant 
      RT_11 = 1.0

      RETURN
      END

